# workflow --> pipeline
name: CI Pipeline

# event --> trigger
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# how syntax will look like for job 

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        #actual command
    - name: Build Command
      run: echo "Building App" 

  Test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        #actual command
    - name : Install Dependencies
      run: npm install

    - name: Test Command
      run: echo "Testing App"

    - name: Run Tests
      run: npm test

  # - name : Test cases ran successfully
  #   run: echo "Test cases ran successfully"